
import Clibgit2
@testable import Git
import XCTest

final class GitErrorTests: XCTestCase {

    func testCatching() {
        XCTAssertEqual(GitError.catching { throw GitError(code: .unknown) }, GIT_ERROR.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .notFound) }, GIT_ENOTFOUND.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .exists) }, GIT_EEXISTS.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .ambiguous) }, GIT_EAMBIGUOUS.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .buffer) }, GIT_EBUFS.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .user) }, GIT_EUSER.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .bareRepository) }, GIT_EBAREREPO.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .unbornBranch) }, GIT_EUNBORNBRANCH.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .unmerged) }, GIT_EUNMERGED.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .nonFastForward) }, GIT_ENONFASTFORWARD.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .invalidSpec) }, GIT_EINVALIDSPEC.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .conflict) }, GIT_ECONFLICT.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .locked) }, GIT_ELOCKED.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .modified) }, GIT_EMODIFIED.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .auth) }, GIT_EAUTH.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .certificate) }, GIT_ECERTIFICATE.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .applied) }, GIT_EAPPLIED.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .peel) }, GIT_EPEEL.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .endOfFile) }, GIT_EEOF.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .invalid) }, GIT_EINVALID.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .uncommitted) }, GIT_EUNCOMMITTED.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .directory) }, GIT_EDIRECTORY.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .mergeConflict) }, GIT_EMERGECONFLICT.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .passthrough) }, GIT_PASSTHROUGH.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .iteratorOver) }, GIT_ITEROVER.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .retry) }, GIT_RETRY.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .mismatch) }, GIT_EMISMATCH.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .indexDirty) }, GIT_EINDEXDIRTY.rawValue)
        XCTAssertEqual(GitError.catching { throw GitError(code: .applyFail) }, GIT_EAPPLYFAIL.rawValue)

        struct Failure: Error {}
        XCTAssertEqual(GitError.catching { throw Failure() }, GIT_EUSER.rawValue)
    }

    func testDomain() {
        XCTAssertEqual(GitError.Domain.none.description, "None")
        XCTAssertEqual(GitError.Domain.noMemory.description, "No Memory")
        XCTAssertEqual(GitError.Domain.os.description, "OS")
        XCTAssertEqual(GitError.Domain.invalid.description, "Invalid")
        XCTAssertEqual(GitError.Domain.reference.description, "Reference")
        XCTAssertEqual(GitError.Domain.zlib.description, "zlib")
        XCTAssertEqual(GitError.Domain.repository.description, "Repository")
        XCTAssertEqual(GitError.Domain.config.description, "Config")
        XCTAssertEqual(GitError.Domain.regex.description, "Regex")
        XCTAssertEqual(GitError.Domain.odb.description, "ODB")
        XCTAssertEqual(GitError.Domain.index.description, "Index")
        XCTAssertEqual(GitError.Domain.object.description, "Object")
        XCTAssertEqual(GitError.Domain.net.description, "Net")
        XCTAssertEqual(GitError.Domain.tag.description, "Tag")
        XCTAssertEqual(GitError.Domain.tree.description, "Tree")
        XCTAssertEqual(GitError.Domain.indexer.description, "Indexer")
        XCTAssertEqual(GitError.Domain.ssl.description, "SSL")
        XCTAssertEqual(GitError.Domain.submodule.description, "Submodule")
        XCTAssertEqual(GitError.Domain.thread.description, "Thread")
        XCTAssertEqual(GitError.Domain.stash.description, "Stash")
        XCTAssertEqual(GitError.Domain.checkout.description, "Checkout")
        XCTAssertEqual(GitError.Domain.fetchhead.description, "Fetch HEAD")
        XCTAssertEqual(GitError.Domain.merge.description, "Merge")
        XCTAssertEqual(GitError.Domain.ssh.description, "SSH")
        XCTAssertEqual(GitError.Domain.filter.description, "Filter")
        XCTAssertEqual(GitError.Domain.revert.description, "Revert")
        XCTAssertEqual(GitError.Domain.callback.description, "Callback")
        XCTAssertEqual(GitError.Domain.cherrypick.description, "Cherrypick")
        XCTAssertEqual(GitError.Domain.describe.description, "Describe")
        XCTAssertEqual(GitError.Domain.rebase.description, "Rebase")
        XCTAssertEqual(GitError.Domain.filesystem.description, "File System")
        XCTAssertEqual(GitError.Domain.patch.description, "Patch")
        XCTAssertEqual(GitError.Domain.worktree.description, "Worktree")
        XCTAssertEqual(GitError.Domain.sha.description, "SHA")
        XCTAssertEqual(GitError.Domain.http.description, "HTTP")
        XCTAssertEqual(GitError.Domain.internal.description, "Internal")
    }

    func testCode() {
        XCTAssertEqual(GitError.Code.unknown.description, "General error.")
        XCTAssertEqual(GitError.Code.notFound.description, "Requested object could not be found.")
        XCTAssertEqual(GitError.Code.exists.description, "Object exists preventing operation.")
        XCTAssertEqual(GitError.Code.ambiguous.description, "More than one object matches.")
        XCTAssertEqual(GitError.Code.buffer.description, "Output buffer too short to hold data.")
        XCTAssertEqual(GitError.Code.bareRepository.description, "Operation not allowed on bare repository.")
        XCTAssertEqual(GitError.Code.unbornBranch.description, "HEAD refers to branch with no commits.")
        XCTAssertEqual(GitError.Code.unmerged.description, "Merge in progress prevented operation.")
        XCTAssertEqual(GitError.Code.nonFastForward.description, "Reference was not fast-forwardable.")
        XCTAssertEqual(GitError.Code.invalidSpec.description, "Name/ref spec was not in a valid format.")
        XCTAssertEqual(GitError.Code.conflict.description, "Checkout conflicts prevented operation.")
        XCTAssertEqual(GitError.Code.locked.description, "Lock file prevented operation.")
        XCTAssertEqual(GitError.Code.modified.description, "Reference value does not match expected.")
        XCTAssertEqual(GitError.Code.auth.description, "Authentication error.")
        XCTAssertEqual(GitError.Code.certificate.description, "Server certificate is invalid.")
        XCTAssertEqual(GitError.Code.applied.description, "Patch/merge has already been applied.")
        XCTAssertEqual(GitError.Code.peel.description, "The requested peel operation is not possible.")
        XCTAssertEqual(GitError.Code.endOfFile.description, "Unexpected end of file.")
        XCTAssertEqual(GitError.Code.invalid.description, "Invalid operation or input.")
        XCTAssertEqual(GitError.Code.uncommitted.description, "Uncommitted changes in index prevented operation.")
        XCTAssertEqual(GitError.Code.directory.description, "The operation is not valid for a directory.")
        XCTAssertEqual(GitError.Code.mergeConflict.description, "A merge conflict exists and cannot continue.")
        XCTAssertEqual(GitError.Code.passthrough.description, "A user-configured callback refused to act.")
        XCTAssertEqual(GitError.Code.iteratorOver.description, "Signals end of iteration with iterator.")
        XCTAssertEqual(GitError.Code.retry.description, "Internal only.")
        XCTAssertEqual(GitError.Code.mismatch.description, "Hashsum mismatch in object.")
        XCTAssertEqual(GitError.Code.indexDirty.description, "Unsaved changes in the index would be overwritten.")
        XCTAssertEqual(GitError.Code.applyFail.description, "Patch application failed.")
    }
}
